site_name: EIAR
site_url: https://eiar.club
dev_addr: 0.0.0.0:8000
base_url: /
#repo_url: https://github.com/eiar-club/writing
site_dir: docs
docs_dir: source
#github pages requires the site_dir to be /docs of the root folder

markdown_extensions:
  - meta
#  - toc:
#      baselevel: 1

plugins:
  - search
  - tags:
      tags_folder: docs

theme:
  name: material
  logo: assets/thick.png
  favicon: assets/tiny.png
  features:
    - navigation.instant
    - navigation.expand
    - navigation.tabs
#    - toc.integrate
#    - navigation.sections (don't enable this)
#    - navigation.indexes
#    - header.autohide

extra_css:
  - stylesheets/color.css
  - stylesheets/menu.css

nav:
  - 'HOME': 'index.md'
  - 'PATH':
    - 'grimoire-zero/index.md'
    - 'grimoire-zero/a-journal-of-nothing/index.md'
    - 'grimoire-zero/a-journal-of-nothing/spring/index.md'
    - 'grimoire-zero/a-journal-of-nothing/spring/sun-king.md'
    - 'grimoire-zero/a-journal-of-nothing/spring/technique-z017.md'
    - 'grimoire-zero/a-journal-of-nothing/spring/woke.md'
    - 'grimoire-zero/a-journal-of-nothing/spring/9order7.md'
    - 'SUMMER' : 'grimoire-zero/a-journal-of-nothing/summer/index.md'
    - 'grimoire-zero/a-journal-of-nothing/summer/breath.md'
    - 'grimoire-zero/a-journal-of-nothing/summer/writing.md'
    - 'grimoire-zero/a-journal-of-nothing/summer/arobe.md'
    - 'grimoire-zero/a-journal-of-nothing/summer/everyone-but-me-is-you.md'
    - 'FALL' : 'grimoire-zero/a-journal-of-nothing/fall/index.md'
    - 'grimoire-zero/a-journal-of-nothing/fall/upload-complete.md'
    - 'grimoire-zero/a-journal-of-nothing/fall/panalytic.md'
    - 'grimoire-zero/a-journal-of-nothing/fall/golden-number.md'
    - 'grimoire-zero/a-journal-of-nothing/fall/five.md'
    - 'WINTER' : 'grimoire-zero/a-journal-of-nothing/winter/index.md'
    - 'grimoire-zero/a-journal-of-nothing/winter/miro-ii.md'
    - 'grimoire-zero/a-journal-of-nothing/winter/miro.md'
    - 'grimoire-zero/a-journal-of-nothing/winter/cosmos.md'
    - 'grimoire-zero/a-journal-of-nothing/winter/skyclad.md'
    - 'A MAN OF EVERYTHING' : 'grimoire-zero/a-man-of-everything/index.md'
    - 'AIR' : 'grimoire-zero/a-man-of-everything/air/index.md'
    - 'grimoire-zero/a-man-of-everything/air/vgnhycr.md'
    - 'grimoire-zero/a-man-of-everything/air/strange-space.md'
    - 'grimoire-zero/a-man-of-everything/air/atthree.md'
    - 'grimoire-zero/a-man-of-everything/air/thrown-away.md'
    - 'FIRE' : 'grimoire-zero/a-man-of-everything/fire/index.md'
    - 'grimoire-zero/a-man-of-everything/fire/key.md'
    - 'grimoire-zero/a-man-of-everything/fire/somber.md'
    - 'grimoire-zero/a-man-of-everything/fire/lamp.md'
    - 'grimoire-zero/a-man-of-everything/fire/routine.md'
    - 'WATER' : 'grimoire-zero/a-man-of-everything/water/index.md'
    - 'grimoire-zero/a-man-of-everything/water/spiral.md'
    - 'grimoire-zero/a-man-of-everything/water/plasma.md'
    - 'grimoire-zero/a-man-of-everything/water/snakes.md'
    - 'grimoire-zero/a-man-of-everything/water/left-handed.md'
    - 'EARTH' : 'grimoire-zero/a-man-of-everything/earth/index.md'
    - 'grimoire-zero/a-man-of-everything/earth/camera.md'
    - 'grimoire-zero/a-man-of-everything/earth/wheel.md'
    - 'grimoire-zero/a-man-of-everything/earth/remnants.md'
    - 'grimoire-zero/a-man-of-everything/earth/wnge.md'
  - 'OVERTURE':
    - 'tome-of-the-harbinger/index.md'
    - 'tome-of-the-harbinger/star-herald/index.md'
    - 'tome-of-the-harbinger/star-herald/galactic/index.md'
    - 'tome-of-the-harbinger/star-herald/galactic/rust.md'
    - 'tome-of-the-harbinger/star-herald/galactic/mirrors.md'
    - 'tome-of-the-harbinger/star-herald/galactic/boomer.md'
    - 'tome-of-the-harbinger/star-herald/galactic/hard-wired.md'
    - 'tome-of-the-harbinger/star-herald/ecliptic/index.md'
    - 'tome-of-the-harbinger/star-herald/ecliptic/dimensionality.md'
    - 'tome-of-the-harbinger/star-herald/ecliptic/savages-in-shiny-cars.md'
    - 'tome-of-the-harbinger/star-herald/ecliptic/tesseract.md'
    - 'tome-of-the-harbinger/star-herald/ecliptic/formless.md'
    - 'tome-of-the-harbinger/star-herald/equatorial/index.md'
    - 'tome-of-the-harbinger/star-herald/equatorial/chain.md'
    - 'tome-of-the-harbinger/star-herald/equatorial/momentum.md'
    - 'tome-of-the-harbinger/star-herald/equatorial/littles.md'
    - 'tome-of-the-harbinger/star-herald/equatorial/un-viaje-con-los-duendes.md'
    - 'tome-of-the-harbinger/star-herald/celestial/index.md'
    - 'BLANK' : 'tome-of-the-harbinger/star-herald/celestial/blank.md'
    - 'tome-of-the-harbinger/star-herald/celestial/army-of-god.md'
    - 'tome-of-the-harbinger/star-herald/celestial/blank.md'
    - 'tome-of-the-harbinger/star-herald/celestial/reflections.md'
    - 'tome-of-the-harbinger/lunar-overture/index.md'
    - 'tome-of-the-harbinger/lunar-overture/twilight/index.md'
    - 'BLANK' : tome-of-the-harbinger/lunar-overture/twilight/blank.md'
    - 'tome-of-the-harbinger/lunar-overture/twilight/x.md'
    - 'tome-of-the-harbinger/lunar-overture/twilight/blank.md'
    - 'tome-of-the-harbinger/lunar-overture/twilight/y.md'
    - 'tome-of-the-harbinger/lunar-overture/dawn/index.md'
    - 'BLANK' : 'tome-of-the-harbinger/lunar-overture/dawn/blank.md'
    - 'tome-of-the-harbinger/lunar-overture/dawn/to-write-or-not.md'
    - 'tome-of-the-harbinger/lunar-overture/dawn/blank.md'
    - 'tome-of-the-harbinger/lunar-overture/dawn/west-west.md'
    - 'tome-of-the-harbinger/lunar-overture/dusk/index.md'
    - 'BLANK' : tome-of-the-harbinger/lunar-overture/dusk/blank.md'
    - 'tome-of-the-harbinger/lunar-overture/dusk/cosmic-interpretation.md'
    - 'tome-of-the-harbinger/lunar-overture/dusk/blank.md'
    - 'tome-of-the-harbinger/lunar-overture/dusk/topi-tapa.md'
    - 'tome-of-the-harbinger/lunar-overture/night/index.md'
    - 'BLANK' : tome-of-the-harbinger/lunar-overture/night/blank.md'
    - 'tome-of-the-harbinger/lunar-overture/night/x.md'
    - 'tome-of-the-harbinger/lunar-overture/night/blank.md'
    - 'tome-of-the-harbinger/lunar-overture/night/y.md'
  - 'ABOUT' : about.md

