site_name: EIAR
site_url: https://eiar.club
dev_addr: 0.0.0.0:8000
#repo_url: https://github.com/eiar-club/writing
site_dir: docs
docs_dir: source
#github pages requires the site_dir to be /docs of the root folder

markdown_extensions:
  - meta
#  - toc:
#      baselevel: 1

plugins:
  - search
  - tags:
      tags_folder: docs

theme:
  name: material
  logo: assets/logo.png
  favicon: assets/tiny.png
  features:
#    - toc.integrate
    - navigation.instant
#    - navigation.indexes
    - navigation.tabs
#    - navigation.sections (don't enable this)
    - navigation.expand
#    - header.autohide

extra_css:
  - stylesheets/color.css

nav:
  - 'HOME': 'index.md'
  - 'PATH':
    - 'grimoire-zero/index.md'
    - 'grimoire-zero/a-journal-of-nothing/index.md'
    - 'grimoire-zero/a-journal-of-nothing/spring/index.md'
    - 'grimoire-zero/a-journal-of-nothing/spring/technique-z017.md'
    - 'grimoire-zero/a-journal-of-nothing/spring/9order7.md'
    - 'SUMMER' : 'grimoire-zero/a-journal-of-nothing/summer/index.md'
    - 'grimoire-zero/a-journal-of-nothing/summer/writing.md'
    - 'grimoire-zero/a-journal-of-nothing/summer/everyone-but-me-is-you.md'
    - 'FALL' : 'grimoire-zero/a-journal-of-nothing/fall/index.md'
    - 'grimoire-zero/a-journal-of-nothing/fall/upload-complete.md'
    - 'grimoire-zero/a-journal-of-nothing/fall/panalytic.md'
    - 'grimoire-zero/a-journal-of-nothing/fall/routine.md'
    - 'grimoire-zero/a-journal-of-nothing/fall/five.md'
    - 'WINTER' : 'grimoire-zero/a-journal-of-nothing/winter/index.md'
    - 'grimoire-zero/a-journal-of-nothing/winter/miro.md'
    - 'grimoire-zero/a-journal-of-nothing/winter/skyclad.md'
    - 'A MAN OF EVERYTHING' : 'grimoire-zero/a-man-of-everything/index.md'
    - 'AIR' : 'grimoire-zero/a-man-of-everything/air/index.md'
    - 'grimoire-zero/a-man-of-everything/air/strange-space.md'
    - 'grimoire-zero/a-man-of-everything/air/thrown-away.md'
    - 'FIRE' : 'grimoire-zero/a-man-of-everything/fire/index.md'
    - 'WATER' : 'grimoire-zero/a-man-of-everything/water/index.md'
    - 'EARTH' : 'grimoire-zero/a-man-of-everything/earth/index.md'
  - 'ABOUT' : about.md

